package com.woniu.pojo;
// Generated 2019-12-18 21:41:06 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Checkintype generated by hbm2java
 */
public class Checkintype implements java.io.Serializable {

	private Integer checkInTypeId;
	private String checkInTypeName;
	private Set checkins = new HashSet(0);

	public Checkintype() {
	}

	public Checkintype(String checkInTypeName, Set checkins) {
		this.checkInTypeName = checkInTypeName;
		this.checkins = checkins;
	}

	public Integer getCheckInTypeId() {
		return this.checkInTypeId;
	}

	public void setCheckInTypeId(Integer checkInTypeId) {
		this.checkInTypeId = checkInTypeId;
	}

	public String getCheckInTypeName() {
		return this.checkInTypeName;
	}

	public void setCheckInTypeName(String checkInTypeName) {
		this.checkInTypeName = checkInTypeName;
	}

	public Set getCheckins() {
		return this.checkins;
	}

	public void setCheckins(Set checkins) {
		this.checkins = checkins;
	}

	@Override
	public String toString() {
		return "Checkintype [checkInTypeName=" + checkInTypeName + "]";
	}

	
}
