package com.woniu.pojo;
// Generated 2019-12-18 21:41:06 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Overman generated by hbm2java
 */
public class Overman implements java.io.Serializable {

	private Integer overmanId;
	private User user;
	private String overmanName;
	private Set clazzs = new HashSet(0);
	private Set users = new HashSet(0);

	public Overman() {
	}

	public Overman(User user, String overmanName, Set clazzs, Set users) {
		this.user = user;
		this.overmanName = overmanName;
		this.clazzs = clazzs;
		this.users = users;
	}

	public Integer getOvermanId() {
		return this.overmanId;
	}

	public void setOvermanId(Integer overmanId) {
		this.overmanId = overmanId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getOvermanName() {
		return this.overmanName;
	}

	public void setOvermanName(String overmanName) {
		this.overmanName = overmanName;
	}

	public Set getClazzs() {
		return this.clazzs;
	}

	public void setClazzs(Set clazzs) {
		this.clazzs = clazzs;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

	@Override
	public String toString() {
		return "Overman [overmanId=" + overmanId + ", overmanName=" + overmanName + "]";
	}

	
	
	

}
