package com.woniu.pojo;
// Generated 2019-12-18 21:41:06 by Hibernate Tools 5.4.7.Final

/**
 * Relationship1 generated by hbm2java
 */
public class Relationship1 implements java.io.Serializable {

	private Integer userRoleId;
	private Role role;
	private User user;

	public Relationship1() {
	}

	public Relationship1(Role role, User user) {
		this.role = role;
		this.user = user;
	}

	public Integer getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Integer userRoleId) {
		this.userRoleId = userRoleId;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Override
	public String toString() {
		return "Relationship1 [userRoleId=" + userRoleId + ", role=" + role + ", user=" + user.getUserId() + "]";
	}

	
}
