package com.woniu.pojo;
// Generated 2019-12-18 21:41:06 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer roleId;
	private String roleName;
	private Set relationship1s = new HashSet(0);

	public Role() {
	}

	public Role(String roleName, Set relationship1s) {
		this.roleName = roleName;
		this.relationship1s = relationship1s;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set getRelationship1s() {
		return this.relationship1s;
	}

	public void setRelationship1s(Set relationship1s) {
		this.relationship1s = relationship1s;
	}

}
