package com.woniu.pojo;
// Generated 2019-12-18 21:41:06 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Stage generated by hbm2java
 */
public class Stage implements java.io.Serializable {

	private Integer stageId;
	private String stageName;
	private Integer stageWeek;
	private Set clazzs = new HashSet(0);

	public Stage() {
	}

	public Stage(String stageName, Integer stageWeek, Set clazzs) {
		this.stageName = stageName;
		this.stageWeek = stageWeek;
		this.clazzs = clazzs;
	}

	public Integer getStageId() {
		return this.stageId;
	}

	public void setStageId(Integer stageId) {
		this.stageId = stageId;
	}

	public String getStageName() {
		return this.stageName;
	}

	public void setStageName(String stageName) {
		this.stageName = stageName;
	}

	public Integer getStageWeek() {
		return this.stageWeek;
	}

	public void setStageWeek(Integer stageWeek) {
		this.stageWeek = stageWeek;
	}

	public Set getClazzs() {
		return this.clazzs;
	}

	public void setClazzs(Set clazzs) {
		this.clazzs = clazzs;
	}

}
