package com.woniu.pojo;
// Generated 2019-12-18 21:41:06 by Hibernate Tools 5.4.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	@Override
	public String toString() {
		return "Student [studentId=" + studentId + ", studentName=" + studentName + ", studentSex=" + studentSex
				+ "]";
	}

	private Integer studentId;
	private Clazz clazz;
	private User user;
	private String studentName;
	private String sutdentCode;
	private String studentSex;
	private String studentPhone;
	private String studentAddress;
	private String studentEdu;
	private String studentCollege;
	private String studentProfessional;
	private Date studentGraduateTime;
	private Set checkins = new HashSet(0);
	private Set scores = new HashSet(0);
	private Set users = new HashSet(0);

	public Student() {
	}

	public Student(Clazz clazz, User user, String studentName, String sutdentCode, String studentSex,
			String studentPhone, String studentAddress, String studentEdu, String studentCollege,
			String studentProfessional, Date studentGraduateTime, Set checkins, Set scores, Set users) {
		this.clazz = clazz;
		this.user = user;
		this.studentName = studentName;
		this.sutdentCode = sutdentCode;
		this.studentSex = studentSex;
		this.studentPhone = studentPhone;
		this.studentAddress = studentAddress;
		this.studentEdu = studentEdu;
		this.studentCollege = studentCollege;
		this.studentProfessional = studentProfessional;
		this.studentGraduateTime = studentGraduateTime;
		this.checkins = checkins;
		this.scores = scores;
		this.users = users;
	}

	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	public Clazz getClazz() {
		return this.clazz;
	}

	public void setClazz(Clazz clazz) {
		this.clazz = clazz;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	public String getSutdentCode() {
		return this.sutdentCode;
	}

	public void setSutdentCode(String sutdentCode) {
		this.sutdentCode = sutdentCode;
	}

	public String getStudentSex() {
		return this.studentSex;
	}

	public void setStudentSex(String studentSex) {
		this.studentSex = studentSex;
	}

	public String getStudentPhone() {
		return this.studentPhone;
	}

	public void setStudentPhone(String studentPhone) {
		this.studentPhone = studentPhone;
	}

	public String getStudentAddress() {
		return this.studentAddress;
	}

	public void setStudentAddress(String studentAddress) {
		this.studentAddress = studentAddress;
	}

	public String getStudentEdu() {
		return this.studentEdu;
	}

	public void setStudentEdu(String studentEdu) {
		this.studentEdu = studentEdu;
	}

	public String getStudentCollege() {
		return this.studentCollege;
	}

	public void setStudentCollege(String studentCollege) {
		this.studentCollege = studentCollege;
	}

	public String getStudentProfessional() {
		return this.studentProfessional;
	}

	public void setStudentProfessional(String studentProfessional) {
		this.studentProfessional = studentProfessional;
	}

	public Date getStudentGraduateTime() {
		return this.studentGraduateTime;
	}

	public void setStudentGraduateTime(Date studentGraduateTime) {
		this.studentGraduateTime = studentGraduateTime;
	}

	public Set getCheckins() {
		return this.checkins;
	}

	public void setCheckins(Set checkins) {
		this.checkins = checkins;
	}

	public Set getScores() {
		return this.scores;
	}

	public void setScores(Set scores) {
		this.scores = scores;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
