package com.woniu.pojo;
// Generated 2019-12-18 21:41:06 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private Integer teacherId;
	private User user;
	private String teacherName;
	private Set clazzs = new HashSet(0);
	private Set users = new HashSet(0);

	public Teacher() {
	}

	public Teacher(User user, String teacherName, Set clazzs, Set users) {
		this.user = user;
		this.teacherName = teacherName;
		this.clazzs = clazzs;
		this.users = users;
	}

	public Integer getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTeacherName() {
		return this.teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	public Set getClazzs() {
		return this.clazzs;
	}

	public void setClazzs(Set clazzs) {
		this.clazzs = clazzs;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}




	@Override
	public String toString() {
		return "Teacher [teacherId=" + teacherId + ", user=" + user.getUserId() + ", teacherName=" + teacherName + "]";
	}

}
