package com.woniu.pojo;
// Generated 2019-12-18 21:41:06 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private Overman overman;
	private Student student;
	private Teacher teacher;
	private String userName;
	private String userPwd;
	private Set relationship1s = new HashSet(0);
	private Set students = new HashSet(0);
	private Set overmans = new HashSet(0);
	private Set teachers = new HashSet(0);

	public User() {
	}

	public User(Overman overman, Student student, Teacher teacher, String userName, String userPwd, Set relationship1s,
			Set students, Set overmans, Set teachers) {
		this.overman = overman;
		this.student = student;
		this.teacher = teacher;
		this.userName = userName;
		this.userPwd = userPwd;
		this.relationship1s = relationship1s;
		this.students = students;
		this.overmans = overmans;
		this.teachers = teachers;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Overman getOverman() {
		return this.overman;
	}

	public void setOverman(Overman overman) {
		this.overman = overman;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public Set getRelationship1s() {
		return this.relationship1s;
	}

	public void setRelationship1s(Set relationship1s) {
		this.relationship1s = relationship1s;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

	public Set getOvermans() {
		return this.overmans;
	}

	public void setOvermans(Set overmans) {
		this.overmans = overmans;
	}

	public Set getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Set teachers) {
		this.teachers = teachers;
	}

	@Override
	public String toString() {
		return "User [userId=" + userId + ", overman=" + overman + ", student=" + student + ", teacher=" + teacher
				+ ", userName=" + userName + ", userPwd=" + userPwd + ", relationship1s=" + relationship1s
				+ ", students=" + students + ", overmans=" + overmans + ", teachers=" + teachers + "]";
	}

	
}
